SET 'auto.offset.reset'='earliest';

CREATE STREAM ALERT
WITH (KAFKA_TOPIC='alert', PARTITIONS=1, REPLICAS=1) AS
    SELECT f.ROWKEY as F_ROWKEY, b.VEHICLEID, b.Lat, b.Lon, b.TRIPHEADSIGN, b.ROUTEID, f.GEOHASH, b.GEOHASH
    FROM BUS b
    INNER JOIN FENCE f WITHIN 7 days
    ON b.GEOHASH = f.GEOHASH
    WHERE GEO_CONTAINED(b.Lat, b.Lon, f._RAW_DATA)
    EMIT CHANGES;
