SET 'auto.offset.reset'='earliest';

CREATE STREAM FENCE_RAW
  (ROWKEY VARCHAR KEY, type VARCHAR, "properties" MAP<VARCHAR, VARCHAR>,
   geometry MAP<VARCHAR, VARCHAR>, _raw_data VARCHAR)
WITH
  (kafka_topic='fence_raw', value_format='JSON', PARTITIONS=1);

CREATE STREAM FENCE_PRE_PARTITION WITH (KAFKA_TOPIC='fence_pre', PARTITIONS=1, REPLICAS=1) AS
  SELECT GEO_COVERING_GEOHASHES(_raw_data, 5) GEOHASH, *
  FROM FENCE_RAW;

CREATE STREAM FENCE WITH (KAFKA_TOPIC='fence', PARTITIONS=1, REPLICAS=1) AS
  SELECT *
  FROM FENCE_PRE_PARTITION
  PARTITION BY GEOHASH;
