SET 'auto.offset.reset'='earliest';

CREATE STREAM ALERT
WITH (KAFKA_TOPIC='alert') AS
SELECT f.ROWKEY, b.VEHICLEID, b.Lat, b.Lon, b.TRIPHEADSIGN, b.ROUTEID
FROM BUS b
INNER JOIN FENCE f WITHIN 7 days
ON b.UNITY = f.UNITY
WHERE GEO_CONTAINED(b.Lat, b.Lon, f._RAW_DATA)
EMIT CHANGES;
