CREATE STREAM ALERT
WITH (KAFKA_TOPIC='alert') AS
SELECT f.ROWKEY, c.vid, c.lat, c.lon, c.DES, c.RT
FROM CTA c
LEFT JOIN FENCE f WITHIN 7 days
ON c.UNITY = f.UNITY
WHERE GEO_CONTAINED(c.LAT, c.LON, f._RAW_DATA)
EMIT CHANGES;