SET 'auto.offset.reset'='earliest';

CREATE STREAM EXPLODED_BUS
WITH (KAFKA_TOPIC='exploded_bus', VALUE_FORMAT='AVRO', PARTITIONS=1, REPLICAS=1) AS
   SELECT EXPLODE(BUSPOSITIONS) from WMATA_RAW EMIT CHANGES;